CREATE TABLE IF NOT EXISTS config_templates (
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  name   TEXT NOT NULL UNIQUE,
  fields TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);

ALTER TABLE vpn_accounts ADD COLUMN days INTEGER;
ALTER TABLE vpn_accounts ADD COLUMN price INTEGER;